### ISSUE TITLE
README中链接忘记更新了

### ISSUE THREAD

**Issue by wyg1997** [Oneflow-Inc/OneFlow-Benchmark#89]
[Classification/cnns/README](https://github.com/Oneflow-Inc/OneFlow-Benchmark/tree/of_develop_py3/Classification/cnns#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C-requirements)`准备工作 Requirements/关于数据集的说明`中的`数据输入`链接忘记换了。

**Comment by ShawnXuan** [comment]
fixed in [PR #91](https://github.com/Oneflow-Inc/OneFlow-Benchmark/pull/91)
Thanks!
