### ISSUE TITLE
性能测试结果

### ISSUE THREAD

**Issue by nbcsm** [Oneflow-Inc/OneFlow-Benchmark#90]
有性能测试的结果吗？
例如，BERT training在DGX-2上的性能，跟Nvidia版本之间的性能比较。
thanks

**Comment by ShawnXuan** [comment]
我们正在进行一轮测试，可惜不是在DGX-2上。

**Comment by Tron-x** [comment]
提供的bert脚本貌似跑多卡会报错

**Comment by ShawnXuan** [comment]
我没有看到错误日志，先猜测一下原因：
目前运行的脚本里有三个参数：
1.  data_part_num
2.  gpu_num_per_node
3.  num_nodes

通常`data_part_num`需要是`gpu_num_per_node * num_nodes` 的整数倍，因为需要做数据并行，不同的卡处理不同的数据文件，多卡的时候不满足这个条件，所以出错了。
如果是这样，有两个解决方案：
1. 增大数据集中part的个数，样本数据集里只有一个part-0数据集，如果仅仅是为了测试可以拷贝或者软链接成part-1, part-2 ...，然后data_part_num设置成part文件的个数`data_part_num`；或者制作完整的bert数据集，目前体量太大，oneflow没有提供下载链接，可选方案是把[tfrecord转换成ofrecord文件](https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/cn/docs/adv_examples/bert.md#%E4%BD%BF%E7%94%A8%E5%AE%8C%E6%95%B4%E7%9A%84wikipedia--bookcorpus%E6%95%B0%E6%8D%AE%E9%9B%86)
2.  参考 https://github.com/Oneflow-Inc/OneFlow-Benchmark/blob/master/LanguageModeling/BERT/run_squad.py#L82 把pretrain的dataloader限定在cpu0:0, 这样读进来的数据能够自动被split到各个卡上。说到这里，其实个人更建议先用bert去做squad任务或者glue任务，因为有完整的数据集，可以明显看到效果。

如果不是我说的原因，还烦请提供错误日志供我们分析。

非常感谢，我们会持续的改进框架脚本和文档。

**Comment by Tron-x** [comment]
感谢！，我参数设置有点问题，不知是否方便开放一个bert 预训练完整数据集的下载，BookCorpus的数据集现在全网已经找不到了~

**Comment by ShawnXuan** [comment]
Just double check, we don't have bookcorpus dataset either, we use gutenberg dataset cooperating with wiki without been fully tested, it's not ready to be released.

**Comment by weberxie** [comment]
How is the speed of ResNet-50 on V100？

**Comment by ShawnXuan** [comment]
Our test is based on V100 16G, and will announce the result soon.

**Comment by ShawnXuan** [comment]
Please find benchmark test report v1 in [DLPerf](https://github.com/Oneflow-Inc/DLPerf), thanks!
